version: '3.8'

services:
  backend:
    build: ./
    env_file:
      - .env
    ports:
      - 3003:3003
    volumes:
      - logs:/app/logs
      - /app/node_modules # anonymous volume
      - ./:/app

volumes:
  logs:
